---
- hosts: qa-servers
  name: become ansible user and download
  vars:
    x: CHECKSUM=$(curl http://software.xyzcorp.com/enigma-checksum.txt | cut -f1 -d' ')
  tasks:
    - name: download from website
      debug:
        msg: $x
      get_url:
        url: http://software.xyzcorp.com/enigma.tgz
        dest: /tmp/enigma.tgz
        checksum: $x

