- name: variables demo
  hosts: all
  tasks:
    - name: show webserver variables
      debug:
        var: my_web
        tags:
          web

    - name: show
      debug:
        var: my_media
        tags:
          media

    - name: Show host variable
      debug:
        var:my_server:
          tags:
            myserver
