- name: Download a file from a URL
  hosts: localhost
  tasks:
    block:
    - name: "Download a file"
      ansible.builtin.get_url:
         url: "http://apps.l33t.com/transaction_list "
         dest: "/home/ansible/transaction_list"
    - name: " print result"
      ansible.builtin.debug:
         msg: "downloaded"
    rescue:
          ansible.builtin.debug:
            mag: "site is not available, try after some time"