- name: Download a file from a URL
  hosts: localhost
  tasks:
    - name: Download a file
      ansible.builtin.get_url:
        url: "https://example.com/somefile.txt"
        dest: "/path/on/local/machine/somefile.txt"